version: '2'
services:
    db:
        image: postgres:9.4
        volumes:
            - dbdata:/var/lib/postgresql/data
    web:
        # build: ./django
        image: registry.twilley.org/mathuin/pyment
        entrypoint: ./wait-for-it.sh -q db:5432 -- 
        command: gunicorn -b ":8000" pyment.wsgi
        depends_on:
            - db
        environment:
            - PUBLIC_ROOT=/public
            - ALLOWED_HOSTS=web
        expose:
            - "8000"
        volumes:
            - public:/public
    nginx:
        image: nginx:latest
        depends_on:
            - web
        ports:
            - "8000:8000"
        volumes:
            - public:/public
            - ./nginx:/etc/nginx/conf.d
volumes:
    dbdata:
        driver: local
    public:
        driver: local
