version: '2'
services:
    db:
        image: postgres:9.4
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=pyment
            - POSTGRES_PASSWORD=pyment_password
            - POSTGRES_DATABASE=pyment
    web:
        build: .
        command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
        volumes:
            - public:/public
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            -  DATABASE_URL=postgres://pyment:pyment_password@db:5432/pyment
volumes:
    dbdata:
        driver: local
    public:
        driver: local
