version: '2'
services:
    db:
        environment:
            - POSTGRES_USER=pyment
            - POSTGRES_PASSWORD=pyment_password
            - POSTGRES_DATABASE=pyment
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - "./devssl/server.crt:/var/lib/postgresql/server.crt:ro"
            - "./devssl/server.key:/var/lib/postgresql/server.key:ro"
        command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    web:
        build: ./django
        command: gunicorn --access-logfile "-" -b ":8000" pyment.wsgi
        environment:
            - DATABASE_URL=postgres://pyment:pyment_password@db:5432/pyment
            - SECRET_KEY='qkmm6qcxz9npoCxtt8ofRu5vVFeTEfbDIJdmIKiEBIiVCi2ef9'
            - ALLOWED_HOSTS=localhost
